<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- <TargetFramework>net6.0</TargetFramework> -->
    <TargetFramework>net8.0</TargetFramework> <!-- de dotnet package OpenPolicyAgent.Opa.AspNetCore is niet compatibel met net6.0 -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.24" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.2" />
    <PackageReference Include="OpenPolicyAgent.Opa.AspNetCore" Version="0.2.1" />
  </ItemGroup>

</Project>
