volumes:   
  nodemodules:

services:
  spa:
    image: websec-spa
    build:
      context: ./SPA
      dockerfile: Dockerfile
    volumes:
      - ./SPA:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    networks:
     - default 
    ports:
     - 3000:3000

  opa:
    image: openpolicyagent/opa:latest
    volumes:
      - ./OPA/opa.rego:/opa.rego
    networks:
      - default
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level"
      - "debug"
      - "--set=decision_logs.console=true"  # dit zal de logs iets leesbaarder maken
      - "--log-format=json-pretty"  # dit zal de logs iets leesbaarder maken
      - "--addr"
      - ":8181"
      - "/opa.rego"

  api:
    image: websec-api
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5172
    volumes:
      - ./API:/app
    networks:
     - default 
    ports:
     - 5172:5172